"""empty message

Revision ID: 52cc4d523303
Revises: 0d24a9e67224
Create Date: 2018-10-26 15:04:39.624591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "52cc4d523303"
down_revision = "0d24a9e67224"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("articles", sa.Column("slug", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("articles", "slug")
    # ### end Alembic commands ###
