"""empty message

Revision ID: 8797fd59fe52
Revises: 29b421582221
Create Date: 2018-11-01 23:03:58.964058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8797fd59fe52'
down_revision = '29b421582221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('articles', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'updated_at')
    op.drop_column('articles', 'created_at')
    # ### end Alembic commands ###
